FROM maven:4.0.0 AS maven-v1
WORKDIR /App
COPY . .
COPY pom.xml /app
RUN mvn dependency:resolve
RUN mvn clean
RUN mvn package -DskipTests -X

FROM openjdk
EXPOSE 8080
COPY --from=build /app/target/*.jar app.jar
#CMD mvn spring-boot:run
CMD {"java", "-jar", "app.jar"}